### ISSUE TITLE
Support ANTLR4 grammars 

### ISSUE THREAD

**Issue by marcospassos** [codelion/gramtest#13]
Any chances of adding support to ANTLR4?

**Comment by codelion** [comment]
This will require some effort. If you look at the way gramtest works is that it uses the ANTLR grammar for BNF to generate the parser. Even though ANTL4 can be expressed as a grammar in ANTLR4 (see https://github.com/antlr/grammars-v4/tree/master/antlr4), the structure that is exposed by the parser is very generic and I am not sure how we can generate tests so that they would work for any ANTLR4 grammar.
