### ISSUE TITLE
Does not generate error messages / warnings on invalid input

### ISSUE THREAD

**Issue by rscarson** [codelion/gramtest#2]
I just seems to... Not do anything

Command to run it:

    gramtest-0.1-SNAPSHOT.jar -file ./grammar.bnf -tests ./target

Platform is windows 10

My grammar:

https://gist.github.com/rscarson/5013dfabacd48b578e05

**Comment by codelion** [comment]
I tried running it with your grammar and it does give the following error - 

```
line 1:0 extraneous input '<expression>:' expecting {<EOF>, ID}
line 3:1 missing '::=' at '|'
Exception in thread "main" java.lang.NullPointerException
```

The grammar is not in usual BNF syntax. You can have a look at the sample grammars in the repository to see the syntax - https://github.com/codelion/gramtest/tree/master/src/test/resources

**Comment by rscarson** [comment]
I know the syntax is not correct, but i really am getting no output at all

It exits immediately

**Comment by codelion** [comment]
Did you build the project with all dependencies included? It should create an uber jar that can be run directly. May be you can try running with sample grammars first and see if modifying them causes errors to be reported. In any case I am unable to reproduce the issue ¯\_(ツ)_/¯

**Comment by rscarson** [comment]
You dropped this

    \

Screenshot of me running it:

http://i.imgur.com/7Efm8iZ.png

Still getting no output from my updated grammar: https://gist.github.com/rscarson/b25aaadc7572b9f9daa2

**Comment by rscarson** [comment]
Running it this way causing it to wait forever:

    java -jar gramtest-0.1-SNAPSHOT-jar-with-dependencies.jar -file ./grammar.bnf -tests ./target

**Comment by codelion** [comment]
There are still some small issues with the grammar - there is no need to add quotes since anything not in between < > is treated as a literal, there are some productions that have <> missing like INT. 

Most likely it is taking time generating the tests. I haven't really tried it with a grammar so large so it is possible we need some new technique to avoid exhaustive enumeration. I would try with small parts of the grammar first to check if they work, e.g. just the identifiers, letters and digits.

**Comment by rscarson** [comment]
What about a literal < or > character?

**Comment by codelion** [comment]
Something like this should work `compare :: =  <  |  >`
